Beter YouTube floaty

diff --git a/src/bin/initi3 b/src/bin/initi3
--- a/src/bin/initi3
+++ b/src/bin/initi3
@@ -1,16 +1,16 @@
 #!/bin/sh
 #
 # Check if a Plasma session already is running and whether it's possible to connect to X
-kcheckrunning
-kcheckrunning_result=$?
-if test $kcheckrunning_result -eq 0 ; then
-	echo "Plasma seems to be already running on this display."
-	xmessage -geometry 500x100 "Plasma seems to be already running on this display." > /dev/null 2>/dev/null
-	exit 1
-elif test $kcheckrunning_result -eq 2 ; then
-	echo "\$DISPLAY is not set or cannot connect to the X server."
-        exit 1
-fi
+# kcheckrunning
+# kcheckrunning_result=$?
+# if test $kcheckrunning_result -eq 0 ; then
+# 	echo "Plasma seems to be already running on this display."
+# 	xmessage -geometry 500x100 "Plasma seems to be already running on this display." > /dev/null 2>/dev/null
+# 	exit 1
+# elif test $kcheckrunning_result -eq 2 ; then
+# 	echo "\$DISPLAY is not set or cannot connect to the X server."
+#         exit 1
+# fi
 
 # finally, give the session control to the session manager
 # see kdebase/ksmserver for the description of the rest of the startup sequence
